version: 2.1

jobs:
  build_and_deploy:
    docker:
      - image: circleci/node:14

    steps:
      - checkout
      # SSH into the server
      - run:
          name: SSH into the server
          command: ssh -o StrictHostKeyChecking=no -T ${SSH_USERNAME}@${SERVER_ADDRESS} "source ~/.nvm/nvm.sh; cd ~/consize-backend && git add . && git stash && git pull && /root/.nvm/versions/node/v18.19.1/bin/npm i && /root/.nvm/versions/node/v18.19.1/bin/npm run compile && /root/.nvm/versions/node/v18.19.1/bin/pm2 restart 0"
workflows:
  build_and_deploy_work:
    jobs:
      - build_and_deploy:
          filters:
            branches:
              only:
                - main
