// Messages
export const SEND_VERIFICATION_EMAIL = "SEND_VERIFICATION_EMAIL"

export const SEND_FORGOT_PASSWORD_EMAIL = "SEND_FORGOT_PASSWORD_EMAIL"

export const SEND_WELCOME_EMAIL = "SEND_WELCOME_EMAIL"
export const SEND_TEAM_INVITATION = "SEND_TEAM_INVITATION"